### ISSUE TITLE
Keep one file synchronized

### ISSUE THREAD

**Issue by locusf** [beidl/harbour-owncloud#20]
For a feature request, I'd suggest a way to keep a single file synchronized between owncloud and device. I use Zutun.txt app and I'd like to keep my todo.txt synched between my phone and owncloud.

**Comment by beidl** [comment]
Part of https://github.com/beidl/harbour-owncloud/projects/1#card-11392439

**Comment by beidl** [comment]
Duplicate of #17 due to recent changes in development branch, synching files and directories will be handled equally.
