### ISSUE TITLE
401 errors on uploading large images/videos

### ISSUE THREAD

**Issue by jaykijay** [beidl/harbour-owncloud#22]
Hi,
i mentioned getting 401 Errors on uploading Images with your app.
It's now impossible to manually upload taken photos from my Xperia Camera to my Nextcloud ( latest 13 stable).
In Acces Log i get: 
`` "PUT /remote.php/webdav/20180701_171638.jpg HTTP/1.1" 401 426 "-" "Mozilla/5.0"
192.168.178.16 - - [12/Jul/2018:23:07:50 +0200] "PUT /remote.php/webdav/20180701_171638.jpg HTTP/1.1" 401 426 "-" "Mozilla/5.0"
192.168.178.16 - - [12/Jul/2018:23:07:51 +0200] "PUT /remote.php/webdav/20180701_171638.jpg HTTP/1.1" 401 426 "-" "Mozilla/5.0"
192.168.178.16 - - [12/Jul/2018:23:07:51 +0200] "PUT /remote.php/webdav/20180701_171638.jpg HTTP/1.1" 401 426 "-" "Mozilla/5.0"
192.168.178.16 - - [12/Jul/2018:23:07:51 +0200] "PROPPATCH /remote.php/webdav/20180701_171638.jpg HTTP/1.1" 401 426 "-" "Mozilla/5.0"
192.168.178.16 - jayki [12/Jul/2018:23:07:51 +0200] "PROPPATCH /remote.php/webdav/20180701_171638.jpg HTTP/1.1" 404 214 "-" "Mozilla/5.0"``

In Nextcloud log i get:
`Sabre\DAV\Exception\NotAuthenticated: No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured`

Every other Client works, strangely automatic Upload works, too...

**Comment by beidl** [comment]
How did you upload the file, through the client app itself or through the Gallery/Share UI?

**Comment by LinLo** [comment]
I got the same pb, I can't send via Gallery/Share UI (tried several version and the last one 8.1-1). Got Jolla 1.
With the application : 
192.168.2.60 - - [29/Aug/2018:02:01:04 +0200] "PUT /remote.php/webdav/Photos/20180827_194531.jpg HTTP/1.1" **201** 0 "-" "Mozilla/5.0"

With the Gallery/ShareUI:
192.168.2.60 - - [29/Aug/2018:01:59:08 +0200] "PUT /remote.php/webdav/Photos/20180827_194531.jpg HTTP/1.1" **401** 426 "-" "Mozilla/5.0"
192.168.2.60 - - [29/Aug/2018:01:59:08 +0200] "PUT /remote.php/webdav/Photos/20180827_194531.jpg HTTP/1.1" **401** 426 "-" "Mozilla/5.0"
192.168.2.60 - - [29/Aug/2018:01:59:08 +0200] "PUT /remote.php/webdav/Photos/20180827_194531.jpg HTTP/1.1" **401** 426 "-" "Mozilla/5.0"
192.168.2.60 - - [29/Aug/2018:01:59:08 +0200] "PUT /remote.php/webdav/Photos/20180827_194531.jpg HTTP/1.1" **401** 426 "-" "Mozilla/5.0"

I don't know exactly why, in the past 2 hours I can't send files from application too (same 401 error).

I notice that NextCloud application (desktop) is using another link to PUT files:
/remote.php/dav/files/<numbers>/file_path

I hope you will be able to fix it :)
Tell me if you want me to do some other tasks.
Thank you
