### ISSUE TITLE
Feature request: Share to Owncloud

### ISSUE THREAD

**Issue by mickolaine** [beidl/harbour-owncloud#3]
Nice to finally have at least some support for files in Owncloud.

It would be a nice feature to share photos to Owncloud the same way I can send them via Bluetooth or share to facebook, by tapping a photo in gallery and selecting the service. Could you consider including this to your program?

**Comment by beidl** [comment]
Queued for v0.6

**Comment by beidl** [comment]
Fixed in cc8c824a719ae444a161ef487e8ac40022676a0c
