### ISSUE TITLE
Harbour-owncloud-daemon uploads pictures using 3G data connections

### ISSUE THREAD

**Issue by Gummikavalier** [beidl/harbour-owncloud#7]
Daemon doesn't mind using 3G data connection for uploads. Which should be and option, if you ask me, as it is more handy than being restricted to WIFI only.

Installed package is harbour-owncloud-0.4-2.armv7hl from openrepos. Logs will follow if I find any.

**Comment by Gummikavalier** [comment]
**journalctl -b --no-pager | grep harbour-owncloud** shows only this:

>helmi 18 19:45:47 Jolla harbour-owncloud-daemon[18475]: [D] Filesystem::scan:21 - scanning "/home/nemo/Pictures/Camera" 
>helmi 18 19:45:47 Jolla harbour-owncloud-daemon[18475]: [D] Filesystem::scan:42 - existing found "/home/nemo/Pictures/Camera/20140724_001.jpg" 
>helmi 18 19:45:47 Jolla harbour-owncloud-daemon[18475]: [D] Filesystem::scan:42 - existing found "/home/nemo/Pictures/Camera/20150210_009.jpg" 
>helmi 18 19:45:47 Jolla harbour-owncloud-daemon[18475]: [D] Filesystem::scan:42 - existing found "/home/nemo/Pictures/Camera/20150215_014.jpg" 
>helmi 18 19:45:47 Jolla harbour-owncloud-daemon[18475]: [D] Filesystem::scan:42 - existing found "/home/nemo/Pictures/Camera/20150218_001.jpg" 
>helmi 18 19:45:47 Jolla harbour-owncloud-daemon[18475]: [D] Filesystem::scan:42 - existing found "/home/nemo/Pictures/Camera/20150218_002.jpg" 
>helmi 18 19:45:47 Jolla harbour-owncloud-daemon[18475]: [D] Filesystem::scan:42 - existing found "/home/nemo/Pictures/Camera/20150218_003.jpg" 
>helmi 18 19:45:47 Jolla harbour-owncloud-daemon[18475]: [D] Filesystem::scan:42 - existing found "/home/nemo/Pictures/Camera/20150218_004.jpg" 
>helmi 18 19:45:47 Jolla harbour-owncloud-daemon[18475]: [D] Uploader::fileFound:35 - void Uploader::fileFound(QString) adding file to upload "/home/nemo/Pictures/Camera/20150218_005.jpg" 
>helmi 18 19:45:47 Jolla harbour-owncloud-daemon[18475]: [D] Uploader::uploadFile:161 - void Uploader::uploadFile() suspended, not downloading 
>helmi 18 19:45:47 Jolla harbour-owncloud-daemon[18475]: [D] Uploader::uploadFile:179 - destination:  "/Jolla/Camera/20150218_005.jpg" 
>helmi 18 19:46:03 Jolla harbour-owncloud-daemon[18475]: [D] Uploader::uploadFinished:89 - void Uploader::uploadFinished() 
>helmi 18 19:46:03 Jolla harbour-owncloud-daemon[18475]: [D] Uploader::uploadFile:161 - void Uploader::uploadFile() suspended, not downloading 
>helmi 18 19:46:03 Jolla harbour-owncloud-daemon[18475]: [D] Uploader::uploadFile:169 - void Uploader::uploadFile() no files to upload 

I browsed through DAV-messages too, but nothing caught my eye. Do you have any suggestions for strings to grep with?

**Comment by beidl** [comment]
Please run the following command, once on WIFI and once on 3G. Let's see if something is confusing the online status.

gdbus introspect --session --dest com.github.beidl.HarbourOwncloud.Daemon --object-path / --only-properties

**Comment by Gummikavalier** [comment]
Thanks! The bit equivocal name is a reference to an old song... ;)

Here are the results:

With 3g (only):
>node / {
>  interface com.github.beidl.HarbourOwncloud.Daemon.Uploader {
>    properties:
>      readwrite b suspended = false;
>      readonly b online = false;
>      readonly b uploading = false;
>  };
>};

With WIFI (only):
>node / {
>  interface com.github.beidl.HarbourOwncloud.Daemon.Uploader {
>    properties:
>      readwrite b suspended = false;
>      readonly b online = true;
>      readonly b uploading = false;
>  };
>};

When I switched back to 3g only, the "readonly b online" was again false, so that is probably ok.

I noted that when I switched back to 3g only, and took a picture, the upload had stopped working (as it should). It had been working before I enabled WIFI.

Then I launched /usr/bin/harbour-owncloud (still while on 3g):
>[nemo@Jolla ~]$ /usr/bin/harbour-owncloud
>[D] QWaylandEglClientBufferIntegration::QWaylandEglClientBufferIntegration:62 - Using Wayland-EGL
>[W] QQmlImportDatabase::registerPluginTypes:1875 - Module 'Sailfish.Silica' does not contain a module identifier directive - it cannot be protected from external registrations.
>[D] DeclarativeCoverWindow::DeclarativeCoverWindow:63 - DeclarativeCoverWindow: I have a default alpha buffer
>[D] OwnCloudBrowser::testConnectionFinished:75 - BEIDL Finished
>[W] unknown:134 - file:///usr/lib/qt5/qml/Sailfish/Silica/Page.qml:134: TypeError: Cannot read property of null
>[D] DaemonControl::setUploading:26 - Uploading?  true
>[D] DaemonControl::setUploading:26 - Uploading?  false
>[nemo@Jolla ~]$

When the owncloud client had logged in and showed the root view, I noticed that the picture got uploaded (and I was still on 3g).

I closed harbour-owncloud and took another picture. The pictures get still uploaded.

I remember at least one occasion that the same has happened before; I had the impression that updates should happen with 3g, and I was puzzled when they didn't after a reboot. Then I started the harbour-owncloud once, and after that the uploads with 3g happened again.

After this I switched back to WIFI and took a picture. It didn't get uploaded. Harbour-owncloud claimed that photo backup was in process, and it seemed to have been stuck. Checked gdbus: "Readonly b online = true;". Closed harbour-owncloud.

Switched back to 3g. No upload. Started harbour-owncloud and upload happens immediately. "Readonly b online = false;". Snapped a new picture and after closing down the harbour-owncloud the upload still keeps working on 3g.

Summarum: currently uploads work on my Jolla when
1. 3g is on
2. If not yet working, onward from the moment where 3g is on and harbour owncloud gets launched.

and upload does not work:
3. Immediately after a reboot
4. If WIFI has been enabled even once. (And 3g data has been disabled, not sure if that detail is important).

**Comment by beidl** [comment]
Is this still an issue with current versions of harbour-owncloud? Else I'd just close the issue.

**Comment by Gummikavalier** [comment]
I cannot currently install daemon to test it (SFOS 2.1.4.13 specific problem with repos), but I tested it maybe 2 months ago, and the operation was still tricky. At least when the device has been rebooted, the daemon did not start automatically, but only after the first launch of the app.

I'll close this for now; I'll test when I get a chance for it and refer to this again if needed. :)

**Comment by beidl** [comment]
Pushing a new version as we speak/type/internet, has additional fix for this specific issue :)

**Comment by Gummikavalier** [comment]
Whee! Thanks! :+1:
